version: "3.8"
services:
  api:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:academy@pg-db:5432/mydb?schema=public
      - PORT=8080
      - JWT_SECRET=DGR2YRBdSfh1Q6W45UdoOr
    ports:
      - 8080:8080
    depends_on:
      - pg-db
  pg-db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=academy
    volumes:
      - learnhub-db-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  learnhub-db-vol:
    name: d0055a64b9f7343e6302adf81a7095498ff5a6175197c546ac74bf61436f2dc3
